# Generated by Django 5.0.2 on 2024-03-02 19:04

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="author",
            new_name="user",
        ),
        migrations.AddField(
            model_name="note",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
